import type { Metadata } from "next";
import "./globals.css";
import { AccessibilityProvider } from "./_components/acess";


export const metadata: Metadata = {
  title: "Nelp Univôlei",
  description: "Generated by create next app", // Colocar Descrição depois
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <AccessibilityProvider>
          {children}
        </AccessibilityProvider>
      </body>
    </html>
  );
}
